"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import { motion, AnimatePresence, MotionConfig, useReducedMotion, useScroll, useSpring } from "framer-motion";
import CinematicHero from "./cinematic-hero";
import ProjectInquiry, { ProjectRequestPicker, inquiryTypes, whatsappInquiryUrl } from "./project-inquiry";
import { FaWhatsapp } from "react-icons/fa";
import { FiArrowUpRight, FiArrowDown, FiGithub, FiLinkedin, FiDownload, FiMenu, FiX, FiSend, FiMessageSquare, FiCode, FiLayers, FiDatabase, FiCheck, FiTarget, FiCompass } from "react-icons/fi";
import { personalData as person } from "@/utils/data/personal-data";
import { projectsData } from "@/utils/data/projects-data";
import { experiences } from "@/utils/data/experience";
import { educations } from "@/utils/data/educations";

const projectDetails = [
  { challenge: "Clothing production involves people, wages, advances, and daily output. Keeping those workflows connected was the central challenge.", approach: "A full-stack management application brings staff records, production tracking, payments, dashboards, and reporting into one workflow.", features: ["Staff and wage management", "Advance payment tracking", "Production dashboards and reports"] },
  { challenge: "Research scattered across web pages is difficult to compare and turn into a coherent brief.", approach: "The application accepts 1-10 web sources, scrapes content, and uses LLM-assisted synthesis to produce a structured brief with database storage and health monitoring.", features: ["Multi-source research input", "LLM-assisted brief generation", "Persistent storage and health monitoring"] },
  { challenge: "A portfolio should make a developer's work easy to explore and give visitors a clear way to connect.", approach: "A responsive Next.js experience combines project discovery, accessible navigation, a contact API, and a portfolio-aware AI assistant.", features: ["Responsive project gallery", "Portfolio-aware AI chat", "Contact form and downloadable CV"] },
  { challenge: "A food delivery experience needs a consistent flow from finding a restaurant to placing an order.", approach: "A full-stack platform connects restaurant browsing, cart management, order placement, and an admin workflow for menu updates.", features: ["Restaurant and menu browsing", "Cart and order placement", "Admin menu management"] },
];
const categories = ["All projects", "Full stack", "Front end"];
function Heading({ number, label, children }) { return <div className="section-heading"><div className="eyebrow"><span>{number}</span> {label}</div><h2>{children}</h2></div>; }
function ProjectPreview({ index }) {
  const project = projectsData[index];
  if (project.image) return <div className="preview real-project-preview"><Image src={project.image} alt={`${project.name} website screenshot`} width={1280} height={800} sizes="(max-width: 700px) 90vw, 45vw" className="project-screenshot" /></div>;
  if (index === 0) return <div className="preview dashboard"><div className="mock-window"><div className="mock-sidebar"><b>S<span>hrusti.</span></b><i /><i /><i /><i /></div><div className="mock-content"><div className="mock-top">Production overview <span>● Live</span></div><div className="mock-stats"><div><small>Total production</small><strong>2,840 <em>↗</em></strong></div><div><small>Active staff</small><strong>48</strong></div><div><small>Orders fulfilled</small><strong>126</strong></div></div><div className="mock-chart"><span>Production performance</span><div>{[35, 54, 43, 68, 57, 83, 74, 94, 78, 100, 86, 115].map((h, i) => <i key={i} style={{height:h}} />)}</div></div></div></div><span className="preview-caption">OPERATIONS, BEAUTIFULLY ORGANIZED.</span></div>;
  if (index === 1) return <div className="preview research"><div className="research-window"><div className="tiny-logo">✳ briefly<span>Research, distilled.</span></div><h4>From information<br />to understanding.</h4><div className="mock-search">Paste a source URL <span>↗</span></div><div className="research-result"><span>YOUR RESEARCH BRIEF</span><b>A clearer picture. In minutes.</b><i /><i /><i /><div><small>01 Key findings</small><small>02 Sources</small></div></div></div><span className="preview-caption">LESS NOISE. MORE KNOWLEDGE.</span></div>;
  if (index === 2) return <div className="preview portfolio-preview"><div className="mini-portfolio"><span>AK. <i>Developer portfolio</i></span><h4>Ideas into<br /><em>experiences.</em></h4><div className="mini-orbit" /><small>DESIGN × DEVELOPMENT</small></div></div>;
  return <div className="preview food"><div className="food-window"><div>● fresh<span>Good food. Good mood.</span></div><h4>Your next favorite<br />meal is right here.</h4><div className="food-plates"><span>🥗<small>Fresh & delicious</small></span><span>🍜<small>Made with love</small></span><span>🍕<small>Everyday favorites</small></span></div><b>Explore the menu ↗</b></div></div>;
}
export default function PremiumPortfolio() {
  const reduceMotion = useReducedMotion();
  const { scrollYProgress } = useScroll();
  const scrollScale = useSpring(scrollYProgress, { stiffness: 100, damping: 30, restDelta: 0.001 });
  const [requestType, setRequestType] = useState(inquiryTypes[0]);
  const [selectedProject, setSelectedProject] = useState(null);
  const selectedDetails = selectedProject !== null ? projectsData[selectedProject].details || projectDetails[selectedProject] || {} : {};
  const [activeSection, setActiveSection] = useState("");
  const [menu, setMenu] = useState(false);
  const [filter, setFilter] = useState(categories[0]);
  const [chat, setChat] = useState(false);
  const [messages, setMessages] = useState([{role:"assistant", content:"Hi! I'm Aman's portfolio assistant. Ask me about his projects, skills, or experience."}]);
  const [question, setQuestion] = useState("");
  const [thinking, setThinking] = useState(false);
  const [chatError, setChatError] = useState("");
  const [sending, setSending] = useState(false);
  const [status, setStatus] = useState(null);
  const chatEnd = useRef(null);
  const detailClose = useRef(null);
  const detailTrigger = useRef(null);
  useEffect(() => {
    const sections = document.querySelectorAll("main > section[id], main > section > div[id]");
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) setActiveSection(entry.target.id);
    }), {rootMargin:"-15% 0px -55% 0px"});
    sections.forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    if (selectedProject === null) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    detailClose.current?.focus();
    const keyHandler = event => {
      if (event.key === "Escape") setSelectedProject(null);
      if (event.key === "Tab") {
        const controls = [...document.querySelectorAll(".project-dialog button, .project-dialog a[href]")];
        const first = controls[0]; const last = controls.at(-1);
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
        if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
      }
    };
    document.addEventListener("keydown", keyHandler);
    return () => { document.body.style.overflow = previousOverflow; document.removeEventListener("keydown", keyHandler); detailTrigger.current?.focus(); };
  }, [selectedProject]);
  useEffect(() => { chatEnd.current?.scrollIntoView({behavior:"smooth", block:"nearest"}); }, [messages, thinking]);
  useEffect(() => { if (!chat && !menu) return; const close = e => { if (e.key === "Escape") { setChat(false); setMenu(false); } }; window.addEventListener("keydown",close); return () => window.removeEventListener("keydown",close); }, [chat,menu]);
  async function sendChat(e) { e.preventDefault(); if (!question.trim() || thinking) return; const next = [...messages,{role:"user",content:question.trim()}]; setMessages(next); setQuestion(""); setThinking(true); setChatError(""); try { const response = await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:next.at(-1).content,messages:next})}); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message || "Unable to connect. Please try again."); setMessages([...next,{role:"assistant",content:data.message}]); } catch(e) { setChatError(e.message); } finally { setThinking(false); } }
  async function sendContact(e) { e.preventDefault(); const form = e.currentTarget; setSending(true); setStatus(null); try { const response = await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))}); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.message || "Message could not be sent. Please email me directly."); setStatus({ok:true,text:"Thank you! Your message has been sent."}); form.reset(); setRequestType(inquiryTypes[0]); } catch(e) { setStatus({ok:false,text:e.message}); } finally { setSending(false); } }
  return <MotionConfig reducedMotion="user" transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}>
    <a href="#main" className="skip-link">Skip to content</a>
    <motion.div className="scroll-progress" style={{scaleX:scrollScale}} aria-hidden="true" /><header className="site-header"><a className="wordmark" href="#" aria-label="Aman Kumar home">Aman Kumar</a><nav className={menu ? "navigation open" : "navigation"} aria-label="Main navigation">{[["Work","projects"],["About","about"],["Experience","experience"]].map(([label,id]) => <a key={id} className={activeSection === id ? "nav-active" : ""} aria-current={activeSection === id ? "location" : undefined} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}<a className="nav-contact" href="#hire" onClick={() => setMenu(false)}>Start a project <FiArrowUpRight /></a></nav><button className="menu-toggle" aria-label={menu ? "Close menu" : "Open menu"} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <FiX /> : <FiMenu />}</button></header>
    <main id="main">
      <CinematicHero />
      <div className="tech-strip"><div className="section-wrap"><span>MY EVERYDAY TOOLKIT</span>{["React","Next.js","JavaScript","Node.js","PostgreSQL","Tailwind CSS"].map(tech => <b key={tech}>{tech}</b>)}</div></div>
      <section className="section-wrap section-space" id="projects"><motion.div className="work-heading motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><Heading number="01" label="SELECTED WORK">Built to make<br /><span>a difference.</span></Heading><p>A selection of projects where thoughtful<br className="desktop-break" /> design meets practical engineering.</p></motion.div><div className="project-filters" role="group" aria-label="Filter projects">{categories.map(cat => <button key={cat} aria-pressed={filter === cat} className={filter === cat ? "active" : ""} onClick={() => setFilter(cat)}>{cat}{cat === categories[0] && <span>{String(projectsData.length).padStart(2, "0")}</span>}</button>)}</div><motion.div layout className="project-grid"><AnimatePresence mode="popLayout">{projectsData.map((project,index) => { if (filter === "Full stack" && project.role !== "Full Stack Developer" || filter === "Front end" && project.role !== "Front-End Developer") return null; return <motion.article className="project-card motion-reveal" key={project.id} initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}} layout whileHover={reduceMotion ? {} : {y:-7}} exit={{opacity:0,scale:0.96}}><div className="project-visual"><ProjectPreview index={index} /><span className="concept-label">{projectsData[index]?.image ? "Website screenshot" : "Interface concept"}</span><button className="preview-open" aria-label={`Explore ${project.name}`} onClick={e => { detailTrigger.current = e.currentTarget; setSelectedProject(index); }}><FiArrowUpRight /></button></div><div className="project-info"><div className="project-category">{project.role} <span>{String(index+1).padStart(2, "0")}</span></div><h3>{project.name}</h3><p>{project.description}</p><div className="project-tags">{project.tools.map(tool => <span key={tool}>{tool}</span>)}</div><div className="project-links"><button className="project-detail-link" onClick={e => { detailTrigger.current = e.currentTarget; setSelectedProject(index); }}>Explore project <FiArrowUpRight /></button>{project.demo && <a href={project.demo} target="_blank" rel="noreferrer">View live project <FiArrowUpRight /></a>}{project.code && project.code !== 'https://github.com/aman/portfolio' && <a href={project.code} target="_blank" rel="noreferrer">Source code <FiGithub /></a>}</div></div></motion.article>; })}</AnimatePresence></motion.div><div className="work-footnote"><span>Always curious. Always building.</span><a href={person.github} target="_blank" rel="noreferrer">More on GitHub <FiArrowUpRight /></a></div></section>
      <section className="capabilities-section section-wrap section-space" id="approach"><motion.div className="work-heading motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><Heading number="02" label="HOW I THINK">Good experiences<br /><span>start with intention.</span></Heading><p>From a first idea to the final detail,<br className="desktop-break" /> every decision has a purpose.</p></motion.div><div className="capability-grid">{[
      {icon: <FiCompass />, title:"Understand the problem", text:"Start with the people, the workflow, and what needs to work better. Clarity comes before code.", tag:"DISCOVER"},
      {icon: <FiLayers />, title:"Shape the experience", text:"Make the complex feel simple. Build a clear structure, responsive layouts, and purposeful interactions.", tag:"DESIGN"},
      {icon: <FiCode />, title:"Build the foundation", text:"Connect the interface to reliable data and APIs with readable code that is easier to maintain.", tag:"DEVELOP"},
      {icon: <FiTarget />, title:"Refine the details", text:"Check the flow, improve the small interactions, and make the experience feel consistent across devices.", tag:"REFINE"},
    ].map((item,index) => <motion.article className="capability-card motion-reveal" key={item.title} initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}} layout whileHover={reduceMotion ? {} : {y:-7}} exit={{opacity:0,scale:0.96}}><div className="capability-top">{item.icon}<span>{String(index+1).padStart(2, "0")}</span></div><span className="capability-tag">{item.tag}</span><h3>{item.title}</h3><p>{item.text}</p></motion.article>)}</div></section>
      <section className="about-section" id="about"><div className="section-wrap section-space about-grid"><motion.div className="about-photo motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><Image sizes="(max-width: 700px) 90vw, 40vw" src={person.profile} alt="Aman Kumar" width={560} height={660} className="portrait" /><div className="portrait-label"><span>THE HUMAN BEHIND THE CODE</span><b>Aman Kumar <FiArrowUpRight /></b></div></motion.div><motion.div className="about-copy motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><Heading number="03" label="A LITTLE ABOUT ME">A builder at heart.<br /><span>A learner, always.</span></Heading><p>I’m Aman, a web developer based in Bihar, India. I enjoy bringing ideas to life through clean code and interfaces that feel effortless.</p><p>From managing real manufacturing workflows to making research easier with AI, I’m drawn to work that solves a meaningful problem. Curiosity drives my process; attention to detail shapes the result.</p><div className="about-values"><div><FiLayers /><span>Thoughtful interfaces<small>Clarity in every interaction.</small></span></div><div><FiDatabase /><span>End-to-end thinking<small>From the first pixel to the database.</small></span></div><div><FiCode /><span>Built to grow<small>Clean, maintainable foundations.</small></span></div></div><a className="text-link" href={person.resume} target="_blank" rel="noreferrer">A closer look at my journey <FiArrowUpRight /></a></motion.div></div></section>
      <section className="section-wrap section-space" id="experience"><motion.div className="motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><Heading number="04" label="THE JOURNEY">Learning. Building.<br /><span>Moving forward.</span></Heading></motion.div><div className="journey-grid"><motion.div className="motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><h3 className="column-title">Experience <span>↗</span></h3>{experiences.map(exp => <article className="timeline-item" key={exp.id}><span className="timeline-dot" /><p className="timeline-date">{exp.duration.replace(/[()]/g, "")}</p><h4>{exp.title === "Self Employed" ? "Independent Developer" : exp.title}</h4><p>{exp.title === "Self Employed" ? "Self-directed projects & continuous learning" : exp.company}</p></article>)}</motion.div><motion.div className="motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><h3 className="column-title">Education <span>↗</span></h3>{educations.map(edu => <article className="timeline-item" key={edu.id}><span className="timeline-dot" /><p className="timeline-date">{edu.duration}</p><h4>{edu.title}</h4><p>{edu.institution}</p></article>)}</motion.div></div><motion.div className="skills-panel motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><div><span className="eyebrow">THE STACK</span><h3>The right tools.<br />The right foundation.</h3></div><div className="skill-groups"><div><span>FRONT END</span><p>React · Next.js · JavaScript · HTML · CSS · Tailwind · Vite</p></div><div><span>BACK END & DATA</span><p>Node.js · Express · MySQL · PostgreSQL</p></div><div><span>WORKFLOW</span><p>Git · Responsive design · API integration</p></div></div></motion.div></section>
      <ProjectInquiry onSelect={setRequestType} reduceMotion={reduceMotion} />
      <section id="contact" className="contact-section"><div className="section-wrap section-space contact-grid"><motion.div className="motion-reveal" initial={reduceMotion ? false : {opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}}><div className="eyebrow"><span>05</span> LET’S CONNECT</div><h2>Have something<br />in mind?<br /><span>Let’s build it.</span><FiArrowUpRight /></h2><p>A project, an opportunity, or just a hello.<br />I’d love to hear from you.</p><a className="contact-whatsapp" href={whatsappInquiryUrl(requestType)} target="_blank" rel="noreferrer"><FaWhatsapp /> Connect on WhatsApp <FiArrowUpRight /></a><a className="contact-email" href={`mailto:${person.email}`}>{person.email} <FiArrowUpRight /></a><div className="contact-socials"><a href={person.github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={person.linkedIn} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={`tel:${person.phone}`}>Call me ↗</a></div></motion.div><form className="contact-form reveal" onSubmit={sendContact}><ProjectRequestPicker value={requestType} onChange={setRequestType} /><div className="form-row"><label htmlFor="name">Your name<input id="name" name="name" placeholder="Alex Johnson" autoComplete="name" required maxLength={100} /></label><label htmlFor="email">Email address<input id="email" name="email" type="email" placeholder="alex@company.com" autoComplete="email" required maxLength={100} /></label></div><label htmlFor="phone">Phone <span>(optional)</span><input id="phone" name="phone" type="tel" placeholder="Your phone number" autoComplete="tel" maxLength={20} /></label><label htmlFor="message">What are you thinking?<textarea id="message" name="message" placeholder="Tell me a little about your project or opportunity…" rows={4} required maxLength={500} /></label>{status && <p role="status" className={status.ok ? "form-success" : "form-error"}>{status.text}</p>}<button className="button primary" type="submit" disabled={sending}>{sending ? "Sending…" : "Send message"}<FiArrowUpRight /></button><p className="form-note">Good conversations are where great things begin.</p></form></div></section>
    </main><footer className="site-footer section-wrap"><a className="wordmark" href="#">Aman Kumar</a><span>© {new Date().getFullYear()} Aman Kumar</span><span>Crafted with care. Built with purpose.</span><a href="#">Back to top ↑</a></footer>
    <button className="chat-trigger" onClick={() => setChat(!chat)} aria-expanded={chat} aria-controls="portfolio-chat" aria-label={chat ? "Close portfolio assistant" : "Ask the portfolio assistant"}>{chat ? <FiX /> : <><FiMessageSquare /><span>Ask about Aman</span><i /></>}</button>
    <AnimatePresence>{selectedProject !== null && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:0.2}} className="dialog-backdrop" onClick={e => { if (e.target === e.currentTarget) setSelectedProject(null); }}><motion.section initial={reduceMotion ? false : {y:40,scale:0.96}} animate={{y:0,scale:1}} exit={{y:20,scale:0.98}} className="project-dialog" role="dialog" aria-modal="true" aria-labelledby="project-dialog-title"><button ref={detailClose} className="dialog-close" onClick={() => setSelectedProject(null)} aria-label="Close project details"><FiX /></button><div className="dialog-visual"><ProjectPreview index={selectedProject} /><span className="concept-label">{projectsData[selectedProject]?.image ? "Website screenshot" : "Visual concept"}</span></div><div className="dialog-content"><div className="eyebrow">PROJECT {String(selectedProject+1).padStart(2, "0")} / {projectsData[selectedProject].role}</div><h2 id="project-dialog-title">{projectsData[selectedProject].name}</h2><div className="project-tags">{projectsData[selectedProject].tools.map(tool => <span key={tool}>{tool}</span>)}</div>{selectedDetails.overview && <p className="project-overview">{selectedDetails.overview}</p>}{(selectedDetails.challenge || selectedDetails.approach) && <div className="detail-columns">{selectedDetails.challenge && <div><h3>The challenge</h3><p>{selectedDetails.challenge}</p></div>}{selectedDetails.approach && <div><h3>The approach</h3><p>{selectedDetails.approach}</p></div>}</div>}{selectedDetails.features?.length > 0 && <><h3 className="feature-title">Key features</h3><ul className="feature-list">{selectedDetails.features.map(feature => <li key={feature}><FiCheck /> {feature}</li>)}</ul></>}<div className="dialog-actions">{projectsData[selectedProject].demo && <a className="button primary" href={projectsData[selectedProject].demo} target="_blank" rel="noreferrer">View live project <FiArrowUpRight /></a>}<a className="button secondary" href="#contact" onClick={() => setSelectedProject(null)}>Discuss a similar project <FiArrowUpRight /></a></div></div></motion.section></motion.div>}
    </AnimatePresence>
    <AnimatePresence>{chat && <motion.aside initial={{opacity:0,y:20,scale:0.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10,scale:0.96}} className="chat-panel" id="portfolio-chat" aria-label="Portfolio assistant"><div className="chat-heading"><div><span className="chat-avatar">a.</span><span><b>Aman’s assistant</b><small>Projects, skills & experience</small></span></div><button onClick={() => setChat(false)} aria-label="Close assistant"><FiX /></button></div><div className="chat-suggestions">{["What has Aman built?", "What are his skills?"].map(q => <button key={q} disabled={thinking} onClick={() => setQuestion(q)}>{q} <FiArrowUpRight /></button>)}</div><div className="chat-messages" role="log" aria-live="polite">{messages.map((m,i) => <p key={i} className={`chat-message ${m.role}`}>{m.content}</p>)}{thinking && <p className="chat-message assistant">Thinking…</p>}{chatError && <p role="alert" className="form-error">{chatError}</p>}<div ref={chatEnd} /></div><form onSubmit={sendChat}><input aria-label="Your question" value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask me anything about Aman…" maxLength={1000} autoFocus /><button disabled={thinking || !question.trim()} aria-label="Send question"><FiSend /></button></form></motion.aside>}</AnimatePresence>
  </MotionConfig>;
}
